- name: set sysctl config
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present
    reload: yes
- name: Update repositories cache and install "python-pip" package
  apt:
    name: [python-pip, python3-pip]
    update_cache: yes
- name: Install docker pip package 
  pip:
    name: docker
- name: Add Docker Repo Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: Add Docker Repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu "{{ansible_distribution_release}}" stable
    state: present
- name: Update repositories cache and install docker-ce package
  apt:
    update_cache: yes 
    name: docker-ce 
    state: present
  